### PR TITLE
Fix Gitalk load error.

### PR DESCRIPTION
**Pull request by AoraMD**

### CODE REVIEW

**Comment by AoraMD** [comment]
Sorry for my careless. Please bring this path into release.

**Comment by AoraMD** [comment]
BTW, can the page design features be merged?

**Review by kamikat — APPROVED** [review]

**Comment by kamikat** [comment]
> BTW, can the page design features be merged?

I'm sorry if I missed anything... Is that a new feature from jekyll 4.x or something else?

**Comment by AoraMD** [comment]
Actually I added a new page template in my forked repository. It can split articles by topics and limit showed articles count. The template looks like that:

screenshot

This is a design-related feature. I wanna know whether it can be merged or not.

**Comment by kamikat** [comment]
It's always good to have more choice. Considering that the topics is somehow an "advanced" feature (which is not that intuitive), it will be better to be an opt-in feature (e.g. an alternative `post-list` page) or at least be compatible with the basic use case.

BTW, I've updated several keys of Gitalk configuration dict for easier documentation and make mermaid integration optional for minimal transfer size. I think we're close to a new release 😼

**Pull request merged**
